version: "3.9"
services:
  db:
    image: mysql/mysql-server:8.0.23
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: petition
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql-mode=""
    volumes:
      - .dbdate:/var/lib/mysql
    ports:
      - 3307:3306
  
    